version = 0.1
[default.deploy.parameters]
stack_name = "apiaccesslogs"
resolve_s3 = true
s3_prefix = "apiaccesslogs"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "ProjectName=\"apiaccesslogs\""
image_repositories = []
